_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 3
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
actnorm:
    value: true
aggregation_method:
    value: sum
attention:
    value: true
augment_noise:
    value: 0
batch_size:
    value: 1024
break_train_epoch:
    value: false
brute_force:
    value: false
clip_grad:
    value: true
condition_time:
    value: true
conditioning:
    value:
        - alpha
cuda:
    value: true
data_augmentation:
    value: false
datadir:
    value: qm9/temp
dataset:
    value: qm9_second_half
dequantization:
    value: deterministic
diffusion_loss_type:
    value: l2
diffusion_noise_precision:
    value: 1e-05
diffusion_noise_schedule:
    value: polynomial_2
diffusion_steps:
    value: 1000
dp:
    value: true
ema_decay:
    value: 0.999
exp_name:
    value: exp_cond_alpha_df_no_causal
filter_n_atoms:
    value: null
generate_epochs:
    value: 1
include_charges:
    value: false
inv_sublayers:
    value: 1
lr:
    value: 0.0001
model:
    value: egnn_dynamics
n_epochs:
    value: 3000
n_layers:
    value: 9
n_report_steps:
    value: 1
n_stability_samples:
    value: 500
nf:
    value: 192
no_cuda:
    value: false
no_wandb:
    value: false
norm_constant:
    value: 1
normalization_factor:
    value: 1
normalize_factors:
    value:
        - 1
        - 8
        - 1
num_workers:
    value: 0
ode_regularization:
    value: 0.001
online:
    value: true
probabilistic_model:
    value: diffusion
remove_h:
    value: false
resume:
    value: null
save_model:
    value: true
sin_embedding:
    value: false
start_epoch:
    value: 0
tanh:
    value: true
test_epochs:
    value: 50
trace:
    value: hutch
visualize_every_batch:
    value: 1e+08
wandb_usr:
    value: null
